# Kosmarium License Compliance Configuration
[licenses]
# Allowed licenses (all permissive, MIT-compatible)
allowed = [
    "MIT",
    "Apache-2.0", 
    "MIT OR Apache-2.0",
    "Apache-2.0/MIT",
    "BSD-2-Clause",
    "BSD-2-Clause OR Apache-2.0 OR MIT",
    "Unlicense",
    "Unlicense OR MIT", 
    "Zlib",
    "MIT OR Zlib OR Apache-2.0",
    "Unicode-3.0",
    "(MIT OR Apache-2.0) AND Unicode-3.0",
    "0BSD",
    "0BSD OR MIT OR Apache-2.0",
    "BSL-1.0",
    "Apache-2.0 OR BSL-1.0"
]

# Explicitly disallowed licenses
denied = [
    "GPL-2.0",
    "GPL-3.0", 
    "LGPL-2.1",
    "LGPL-3.0",
    "AGPL-3.0"
]

confidence-threshold = 0.8

# Exceptions for specific cases
exceptions = [
    { allow = ["Unicode-3.0"], name = "unicode-ident" },
]
